{
  "{{ name }}": {
    "name": "{{ name }}",
    "description": "{{ description }}",
    "entries": [
      {% for site_id in site_ids %}
      {"regular": {{ site_id }}}{% if not loop.last %},{% endif %}
      {% endfor %}
    ]
  }
}
