---
- name: LAN Segments Management
  hosts: localhost
  gather_facts: false
  vars:
    # graphiant_host: "https://api.graphiant.com"
    # graphiant_username: "{{ vault_graphiant_username }}"
    # graphiant_password: "{{ vault_graphiant_password }}"

    # Use YAML anchors to avoid repetition
    graphiant_client_params: &graphiant_client_params
      host: "{{ graphiant_host | default(lookup('env', 'GRAPHIANT_HOST')) }}"
      username: "{{ graphiant_username | default(lookup('env', 'GRAPHIANT_USERNAME')) }}"
      password: "{{ graphiant_password | default(lookup('env', 'GRAPHIANT_PASSWORD')) }}"
      
      # host: "{{ lookup('ini', 'url file=test/test.ini section=host') }}"
      # username: "{{ lookup('ini', 'username file=test/test.ini section=credentials') }}"
      # password: "{{ lookup('ini', 'password file=test/test.ini section=credentials') }}"

  tasks:
    - name: Configure Global LAN Segments
      graphiant.graphiant_playbooks.graphiant_global_config:
        <<: *graphiant_client_params
        config_file: "sample_lan_segments.yaml"
        operation: "configure_lan_segments"
        detailed_logs: true  # Enable detailed logging to see library operations
        state: present
      register: configure_result

    - name: Display Configuration Results
      debug:
        msg: "{{ configure_result.msg }}"

    - name: Deconfigure Global LAN Segments
      graphiant.graphiant_playbooks.graphiant_global_config:
        <<: *graphiant_client_params
        config_file: "sample_lan_segments.yaml"
        operation: "deconfigure_lan_segments"
        detailed_logs: true  # Enable detailed logging to see library operations
        state: absent
      register: deconfigure_result

    - name: Display Deconfiguration Results
      debug:
        msg: "{{ deconfigure_result.msg }}"

    - name: Configure Global LAN Segments
      graphiant.graphiant_playbooks.graphiant_global_config:
        <<: *graphiant_client_params
        config_file: "sample_lan_segments.yaml"
        operation: "configure_lan_segments"
        detailed_logs: true  # Enable detailed logging to see library operations
        state: present
      register: configure_result

    - name: Display Configuration Results
      debug:
        msg: "{{ configure_result.msg }}"