---
- name: Data Exchange Proxy Tenant Prerequisites
  hosts: localhost
  gather_facts: false
  vars:
    #graphiant_host: "https://api.graphiant.com"
    #graphiant_username: "{{ vault_graphiant_username }}"
    #graphiant_password: "{{ vault_graphiant_password }}"
    
    # Use YAML anchors to avoid repetition
    graphiant_client_params: &graphiant_client_params
      host: "{{ graphiant_host | default(lookup('env', 'GRAPHIANT_HOST')) }}"
      username: "{{ graphiant_username | default(lookup('env', 'GRAPHIANT_USERNAME')) }}"
      password: "{{ graphiant_password | default(lookup('env', 'GRAPHIANT_PASSWORD')) }}"
      #host: "{{ graphiant_host | default(lookup('ini', 'url file=/absolute/path/test/test.ini section=host')) }}"
      #username: "{{ graphiant_username | default(lookup('ini', 'username file=/absolute/path/test/test.ini section=credentials')) }}"
      #password: "{{ graphiant_password | default(lookup('ini', 'password file=/absolute/path/test/test.ini section=credentials')) }}"

  tasks:
    - name: Configure Global VPN Profiles
      graphiant.graphiant_playbooks.graphiant_global_config:
        <<: *graphiant_client_params
        config_file: "sample_global_vpn_profiles.yaml"
        operation: "configure_vpn_profiles"
        detailed_logs: true  
        state: present
      register: configure_vpn_profiles_result
      tags: ['prerequisites', 'vpn_profiles']

    - name: Display Configuration Results
      debug:
        msg: "{{ configure_vpn_profiles_result.msg }}"
