interfaces:
  - edge-1-sdktest:
    # LAN Sub-Interface (VLAN) with Static IPv4 assignment
    - name: GigabitEthernet4/0/0
      sub_interfaces:
        - vlan: 1
          lan: lan-segment-3
          ipv4: 10.1.1.1/24
          description: lan-segment-3 interface
          alias: Gig3.1
          v4_tcp_mss: 1392
          v6_tcp_mss: 1220

  - edge-2-sdktest:
    # LAN interface with Static IPv4 assignments
    - name: GigabitEthernet4/0/0
      ipv4: 10.1.2.1/24
      lan: lan-segment-3
      description: lan-segment-3 interface
      mtu: 1500
      v4_tcp_mss: 1392
      v6_tcp_mss: 1220

  - edge-3-sdktest:  
    # LAN Interface with Static IPv4/IPv6 assignment
    - name: GigabitEthernet4/0/0
      ipv4: 10.1.3.1/24
      lan: lan-segment-3
      description: lan-segment-3 interface
      mtu: 1500
      v4_tcp_mss: 1392
      v6_tcp_mss: 1220
