# Sample Data Exchange Customers Configuration - Scale Test (50 Financial Customers)
# This file demonstrates how to configure Data Exchange customers at scale
#
# The system will:
# 1. Read customer configuration from the 'data_exchange_customers' list
# 2. Check if customer already exists (idempotent operation)
# 3. POST to v1/extranets-b2b-peering/customer with the payload

data_exchange_customers:
  - name: "FinanceBank-001"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin001@financebank.com"
        - "support001@financebank.com"
      maximumNumberOfSites: 4

  - name: "FinanceBank-002"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin002@financebank.com"
        - "support002@financebank.com"
      maximumNumberOfSites: 6

  - name: "FinanceBank-003"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin003@financebank.com"
        - "support003@financebank.com"
      maximumNumberOfSites: 8

  - name: "FinanceBank-004"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin004@financebank.com"
        - "support004@financebank.com"
      maximumNumberOfSites: 4

  - name: "FinanceBank-005"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin005@financebank.com"
        - "support005@financebank.com"
      maximumNumberOfSites: 10

  - name: "FinanceBank-006"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin006@financebank.com"
        - "support006@financebank.com"
      maximumNumberOfSites: 6

  - name: "FinanceBank-007"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin007@financebank.com"
        - "support007@financebank.com"
      maximumNumberOfSites: 8

  - name: "FinanceBank-008"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin008@financebank.com"
        - "support008@financebank.com"
      maximumNumberOfSites: 4

  - name: "FinanceBank-009"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin009@financebank.com"
        - "support009@financebank.com"
      maximumNumberOfSites: 12

  - name: "FinanceBank-010"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin010@financebank.com"
        - "support010@financebank.com"
      maximumNumberOfSites: 6

  - name: "FinanceBank-011"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin011@financebank.com"
        - "support011@financebank.com"
      maximumNumberOfSites: 8

  - name: "FinanceBank-012"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin012@financebank.com"
        - "support012@financebank.com"
      maximumNumberOfSites: 4

  - name: "FinanceBank-013"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin013@financebank.com"
        - "support013@financebank.com"
      maximumNumberOfSites: 10

  - name: "FinanceBank-014"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin014@financebank.com"
        - "support014@financebank.com"
      maximumNumberOfSites: 6

  - name: "FinanceBank-015"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin015@financebank.com"
        - "support015@financebank.com"
      maximumNumberOfSites: 8

  - name: "FinanceBank-016"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin016@financebank.com"
        - "support016@financebank.com"
      maximumNumberOfSites: 4

  - name: "FinanceBank-017"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin017@financebank.com"
        - "support017@financebank.com"
      maximumNumberOfSites: 14

  - name: "FinanceBank-018"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin018@financebank.com"
        - "support018@financebank.com"
      maximumNumberOfSites: 6

  - name: "FinanceBank-019"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin019@financebank.com"
        - "support019@financebank.com"
      maximumNumberOfSites: 8

  - name: "FinanceBank-020"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin020@financebank.com"
        - "support020@financebank.com"
      maximumNumberOfSites: 4

  - name: "FinanceBank-021"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin021@financebank.com"
        - "support021@financebank.com"
      maximumNumberOfSites: 10

  - name: "FinanceBank-022"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin022@financebank.com"
        - "support022@financebank.com"
      maximumNumberOfSites: 6

  - name: "FinanceBank-023"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin023@financebank.com"
        - "support023@financebank.com"
      maximumNumberOfSites: 8

  - name: "FinanceBank-024"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin024@financebank.com"
        - "support024@financebank.com"
      maximumNumberOfSites: 4

  - name: "FinanceBank-025"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin025@financebank.com"
        - "support025@financebank.com"
      maximumNumberOfSites: 12

  - name: "FinanceBank-026"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin026@financebank.com"
        - "support026@financebank.com"
      maximumNumberOfSites: 6

  - name: "FinanceBank-027"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin027@financebank.com"
        - "support027@financebank.com"
      maximumNumberOfSites: 8

  - name: "FinanceBank-028"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin028@financebank.com"
        - "support028@financebank.com"
      maximumNumberOfSites: 4

  - name: "FinanceBank-029"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin029@financebank.com"
        - "support029@financebank.com"
      maximumNumberOfSites: 16

  - name: "FinanceBank-030"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin030@financebank.com"
        - "support030@financebank.com"
      maximumNumberOfSites: 6

  - name: "FinanceBank-031"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin031@financebank.com"
        - "support031@financebank.com"
      maximumNumberOfSites: 8

  - name: "FinanceBank-032"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin032@financebank.com"
        - "support032@financebank.com"
      maximumNumberOfSites: 4

  - name: "FinanceBank-033"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin033@financebank.com"
        - "support033@financebank.com"
      maximumNumberOfSites: 10

  - name: "FinanceBank-034"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin034@financebank.com"
        - "support034@financebank.com"
      maximumNumberOfSites: 6

  - name: "FinanceBank-035"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin035@financebank.com"
        - "support035@financebank.com"
      maximumNumberOfSites: 8

  - name: "FinanceBank-036"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin036@financebank.com"
        - "support036@financebank.com"
      maximumNumberOfSites: 4

  - name: "FinanceBank-037"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin037@financebank.com"
        - "support037@financebank.com"
      maximumNumberOfSites: 18

  - name: "FinanceBank-038"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin038@financebank.com"
        - "support038@financebank.com"
      maximumNumberOfSites: 6

  - name: "FinanceBank-039"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin039@financebank.com"
        - "support039@financebank.com"
      maximumNumberOfSites: 8

  - name: "FinanceBank-040"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin040@financebank.com"
        - "support040@financebank.com"
      maximumNumberOfSites: 4

  - name: "FinanceBank-041"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin041@financebank.com"
        - "support041@financebank.com"
      maximumNumberOfSites: 10

  - name: "FinanceBank-042"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin042@financebank.com"
        - "support042@financebank.com"
      maximumNumberOfSites: 6

  - name: "FinanceBank-043"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin043@financebank.com"
        - "support043@financebank.com"
      maximumNumberOfSites: 8

  - name: "FinanceBank-044"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin044@financebank.com"
        - "support044@financebank.com"
      maximumNumberOfSites: 4

  - name: "FinanceBank-045"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin045@financebank.com"
        - "support045@financebank.com"
      maximumNumberOfSites: 20

  - name: "FinanceBank-046"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin046@financebank.com"
        - "support046@financebank.com"
      maximumNumberOfSites: 6

  - name: "FinanceBank-047"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin047@financebank.com"
        - "support047@financebank.com"
      maximumNumberOfSites: 8

  - name: "FinanceBank-048"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin048@financebank.com"
        - "support048@financebank.com"
      maximumNumberOfSites: 4

  - name: "FinanceBank-049"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin049@financebank.com"
        - "support049@financebank.com"
      maximumNumberOfSites: 12

  - name: "FinanceBank-050"
    type: "non_graphiant_peer"
    invite:
      adminEmail: 
        - "admin050@financebank.com"
        - "support050@financebank.com"
      maximumNumberOfSites: 6
