---
# Configuration for Graphiant Playbooks Ansible Collection docsite
# This file configures links and communication channels for the collection documentation

# Edit on GitHub links - allows users to create PRs directly from the documentation
edit_on_github:
  repository: Graphiant-Inc/graphiant-playbooks
  branch: main
  # Collection root is in ansible_collections/graphiant/graphiant_playbooks
  path_prefix: 'ansible_collections/graphiant/graphiant_playbooks'

# Extra links that appear on the collection page
extra_links:
  - description: Report an issue
    url: https://github.com/Graphiant-Inc/graphiant-playbooks/issues/new/choose
  - description: View source code
    url: https://github.com/Graphiant-Inc/graphiant-playbooks

# Communication channels for the collection
# Specify where users can get help and discuss the collection
communication:
  forums:
    - topic: Ansible Forum
      url: https://forum.ansible.com/c/help/6/none

# Note: The following links are automatically added from galaxy.yml:
# - Homepage (from homepage field)
# - Repository (from repository field)
# - Documentation (from documentation field)
# - Issues (from issues field)

